### ISSUE TITLE
expyriment -D crash (for a dev version)

### ISSUE THREAD

**Issue by g-rieucau** [expyriment/expyriment-stash#12]
Hello,

    $ expyriment -D
    Expyriment 0.11.dev2 (Python 3.12.0) 
    Main file: /home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/bin/expyriment (ae95f5)

    Expyriment command line interface

    Download from stash
     what to download ([all]/examples/extras/tools)? 
    from which branch? (master/[0.11.dev2])? 

ends in:

    RuntimeError: Download of https://github.com/expyriment/expyriment-stash/archive/0.11.dev2.zip failed!

It would be nice to explain in `README.md` how to install the extras manually (where to git clone the repo, ...)

**Comment by g-rieucau** [comment]
Adding `[all]` to the command line indicated at https://github.com/expyriment/expyriment/releases does not install the extras

    python -m pip install  -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre expyriment[all]

**Comment by fladd** [comment]
Yes, this fails since there is no 0.11.dev2 branch on the Expyriment stash. Once 0.11 final is released, this will work. If you want to download the extras for a dev release, use the option to download the version from the master branch that is given to you when calling `expyriment -D`.

Also note that installing Expyriment with the 'all' option is not supposed to download the extras. The 'all' option is for installing additional dependencies from PyPi.
