### ISSUE TITLE
not able to launch experiment on Linux

### ISSUE THREAD

**Issue by lcnature** [expyriment/expyriment-stash#3]
Hi,
I am new to expyriment. I installed it on Ubuntu 16.06 with the command `pip install expyriment[all]`. There was no complaint during this installation. However, when I tried to run one of the example code snarc_expriment.py, all I saw was these lines printed in the terminal with no stimulus showing on screen at all:
```
Expyriment 0.9.0 (Python 3.6.2) 
snarc_experiment.py
*** NORMAL MODE ***
```

I have also made sure I was using only one monitor of my laptop.

Is there any way I can know what might be wrong?
Thanks!

**Comment by fladd** [comment]
Hi,

I have not seen this before. The output of `expyriment.misc.get_system_info()` would be very helfpul. Also, does the test suite run?

But let's keep issues concerning Expyriment itself in the [Expyriment repo](github.com/expyriment/expyriment). I will close this issue here. Please start a new issue in the Expyriment repo for your reply.
